obfuscator_debug:
    stage: test
    before_script:
        - /bin/bash $CACHE_DIR/ninjaScript.bash "./Scripts/build_vanilla_compiler.sh"
        - /bin/bash Scripts/setup_from_cache.sh
    script:
        - /bin/bash Scripts/build_from_cache.sh
        - /bin/bash Scripts/run_tests_on_ci.sh
        - /bin/bash Scripts/process_build_artifacts.sh
    tags:
        - xcode-9.0
    except:
        - master

obfuscator_master:
    stage: test
    before_script:
        - /bin/bash $CACHE_DIR/ninjaScript.bash "./Scripts/build_vanilla_compiler.sh"
        - /bin/bash Scripts/setup_from_cache.sh
    script:
        - /bin/bash Scripts/build_from_cache.sh
        - /bin/bash Scripts/run_tests_on_ci.sh
        - /bin/bash Scripts/process_build_artifacts.sh
    tags:
        - xcode-9.0
    only:
        - master

obfuscator_release:
    stage: test
    script:
        - /bin/bash Scripts/build.sh
        - /bin/bash Scripts/run_tests_on_ci.sh
        - /bin/bash Scripts/process_build_artifacts.sh
    tags:
        - xcode-9.0
    only:
        - tags

