obfuscator_debug:
    stage: test
    before_script:
        - /bin/bash $CACHE_DIR/ninjaScript.bash
    script:
        - /bin/bash Scripts/build.sh
    tags:
        - xcode-9.0
    only:
        - tags

